### ISSUE TITLE
A mistake

### ISSUE THREAD

**Issue by BlueSsssOvO** [PizzaLovers007/AdofaiTweaks#31] opened 2023-12-09 11:56 UTC
When I was playing Dance of Ice and Fire, this mod didn't work, and I couldn't adjust it anymore
![Uploading 屏幕截图(489).png…]()

**Comment by PizzaLovers007** [comment] 2023-12-10 18:24
Duplicate of #28

**Closed as not planned** 2023-12-10 18:25 UTC
